qg-datapurge-125952a94e2a2233a62dc9293493b73ed2d4c89f/config/routes.rb
Rails.application.routes.draw do
	
	resources :purgings do
		collection do 
			get 'purging_request'
			get 'purging_request_form'
			get 'purge_analytics'
		end
	end

	resources :pgr_requests
	get '/pgr_request/:id/approve' => "pgr_requests#approve"

end

qg-datapurge-125952a94e2a2233a62dc9293493b73ed2d4c89f/app/controllers/pgr_requests_controller.rb
class PgrRequestsController < ApplicationController
	
  #authorize_resource
  #before_filter :authenticate_user!
  #before_filter :block_inactive_user!
  respond_to :json
  include ApplicationHelper

  include Approval2::ControllerAdditions

	def index
		@purge_request = (params[:approval_status].present? and params[:approval_status] == 'U') ? PgrRequest.unscoped.where("approval_status =?",'U').order("id desc") : PgrRequest.order("id desc")
		@purge_request = @purge_request.paginate(:per_page => 10, :page => params[:page]) rescue []
	end

	 def show
  	  @purge_data = PgrRequest.unscoped.find(params[:id])
  	end

  	def approve
  		purge_data = PgrRequest.find(params[:id])
  		purge_data.updated_by = current_user.id
  		purge_data.save

		begin
			if purge_data.table_name == "FUNDS_TRANSFERS"
				plsql.purge_tables_ft2(purge_data.table_name,purge_data.to_date.to_date.strftime("%d-%m-%Y"),current_user.username)
			elsif purge_data.table_name == "INWARD_REMITTANCES"
				plsql.purge_tables_inw(purge_data.table_name,purge_data.to_date.to_date.strftime("%d-%m-%Y"),current_user.username)
			elsif purge_data.table_name == "ECOL_TRANSACTIONS"
				plsql.purge_tables_ecol(purge_data.table_name,purge_data.to_date.to_date.strftime("%d-%m-%Y"),current_user.username)
			elsif purge_data.table_name == "NS_PENDING_NOTIFICATION"
				ActiveRecord::Base.connection.execute("delete ns_pending_notifications where created_at < sysdate - #{purge_data.ns_day_cnt}")	
			end
		rescue Exception => e
			puts "data purge procedure call error #{e}"
		end

		redirect_to '/pgr_requests'
  	end

  	private

    def pgr_request_params
      params.require(:pgr_request).permit(:table_name,:to_date,:lock_version, :approval_status, :last_action, :approved_version, 
                                   :approved_id, :created_by, :updated_by)
    end
end

qg-datapurge-125952a94e2a2233a62dc9293493b73ed2d4c89f/app/controllers/purgings_controller.rb
class PurgingsController < ApplicationController

  #authorize_resource
  #before_filter :authenticate_user!
  #before_filter :block_inactive_user!
  respond_to :json
  include ApplicationHelper
  include Approval2::ControllerAdditions

  def purging_request
    prg_data = PgrRequest.new
    prg_data.table_name = params[:table_name]
    prg_data.to_date = params[:from_date]
    prg_data.created_by = current_user.id
    
    if params.has_key?(:deletion_period)
        prg_data.ns_day_cnt = params[:deletion_period]["return"]
    end  
     
    prg_data.save
    
    respond_to do |format|
      format.js   { render :js => "alert('Request Accepeted Successfully and is pending for approval');" }
    end

  end

  def purge_analytics
    @prg_audit = AuditPurge.all
  end  

end

qg-datapurge-125952a94e2a2233a62dc9293493b73ed2d4c89f/app/views/pgr_requests/_approve.html.haml
- can = can? :approve, @record
- approve_flag = @record.enable_approve_button?
%a.btn{"data-toggle" => "modal", :href => "#{!(can && approve_flag) ? '#' : '#myModalApprove'}", :role => "button", :class => "btn btn-primary #{(can && approve_flag) ? '' : 'disabled'}"} Approve
.modal.hide.fade{"id" => "myModalApprove", "aria-hidden" => "true", "aria-labelledby" => "  myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3#myModalLabel  Approve
    #error_message{:style => 'color:red'}
  .modal-body
    = simple_form_for @record, :url => {:action => 'approve'}, :method => :get, :html=>{:id=>"transition"} do |ef|
      = ef.input :updated_by, :as => :hidden, :input_html => {:value => current_user.id}
      = submit_tag "Approve", :class=>"btn btn-primary transition_button", :id => "transition_button"
%p{:style => 'color:green;'}
  = created_or_edited_by(@record)
%br

qg-datapurge-125952a94e2a2233a62dc9293493b73ed2d4c89f/app/views/pgr_requests/index.html.erb
<br/>
<h1>Data Purge Request</h1>
<br/>

<%= "Total Count: #{@purge_request.count}" %>
<%= will_paginate @purge_request, :page_links => true %>
<br/>
<table class="table table-bordered table-striped table-hover" style="table-layout: fixed; width: 100%;">
  <div class="thead">
    <th style="text-align:left; background-color: lightblue;"></th>
    <th style="text-align:left; background-color: lightblue;">
      TABLE NAME
    </th>
    <th style="text-align:left; background-color: lightblue;">
      To Date
    </th>
    <th style="text-align:left; background-color: lightblue;">
      Created By 			
    </th>
    <th style="text-align:left; background-color: lightblue;">
      Updated By      
    </th>
    <th style="text-align:left; background-color: lightblue;">
      Created At      
    </th>
  </div>
  <div class="tbody">
    <% @purge_request.each do |purge_request| %>
      <tr>
        <td style="text-align:left;">
          <%= link_to 'Show', pgr_request_path(purge_request)%>
        </td>
        <td style="text-align:left;">
          <%= purge_request.try(:table_name)   %>
        </td>
        <td style="text-align:left;">
          <%= purge_request.try(:to_date) %>
        </td>
        <td style="text-align:left;">
          <%= purge_request.created_user.try(:username) %>
        </td>
        <td style="text-align:left;">
          <%= purge_request.updated_user.try(:username) %>
        </td>
        <td style="text-align:left;">
          <%= purge_request.created_at.strftime("%d/%m/%Y") %>
        </td>
      </tr>
    <% end %>
  </div>
</table>

qg-datapurge-125952a94e2a2233a62dc9293493b73ed2d4c89f/app/views/pgr_requests/show.html.haml
.form-horizontal.show_form
  .form-main-with-color{:style=>'background-color: #F1F2F8;'}
    #form-details
      %h3 Data Purge Request
      %br
      %p{:style => 'text-align:left; padding-left:6px; padding-bottom:17px'}
        - can = can? :edit, @purge_data
        = render 'approve', :@record => @purge_data
      %table.table.no-border{:style=>"table-layout: fixed; width: 100%;"}
        %tr
          %td.label Table Name
          %td.value
            = @purge_data.try(:table_name)
          %td
        - if !@purge_data.ns_day_cnt.present?  
          %tr
            %td.label Date
            %td.value
              = @purge_data.try(:to_date)
            %td
        - if @purge_data.ns_day_cnt.present?  
          %tr
            %td.label Day Count
            %td.value
              = @purge_data.try(:ns_day_cnt).capitalize
            %td  
        %tr
          %td.label Created at
          %td.value
            = @purge_data.created_at
          %td  
        %tr
          %td.label Created By
          %td.value
            = @purge_data.created_user.try(:username)
          %td
        %tr
          %td.label Updated By
          %td.value
            = @purge_data.updated_user.try(:username)
          %td  

qg-datapurge-125952a94e2a2233a62dc9293493b73ed2d4c89f/app/views/purgings/purge_analytics.html.erb
<br/>
<h1>Data Purge Analytics</h1>
<br/>
<table class="table table-bordered table-striped table-hover" style="table-layout: fixed; width: 100%;">
  <div class="thead">
    <th style="text-align:left; background-color: lightblue;">
      INSERTION
    </th>
    <th style="text-align:left; background-color: lightblue;">
      DELETION
    </th>
    <th style="text-align:left; background-color: lightblue;">
      RUN BY
    </th>
    <th style="text-align:left; background-color: lightblue;">
      RUN AT     
    </th>
    <th style="text-align:left; background-color: lightblue;">
      TABLE NAME    
    </th>
    <th style="text-align:left; background-color: lightblue;">
      FAULT REASON      
    </th>
    <th style="text-align:left; background-color: lightblue;">
      STATUS     
    </th>
  </div>

  <div class="tbody">
    <% @prg_audit.each do |purge_data| %>
      <tr>
        <td style="text-align:left;">
          <%= purge_data.try(:insertion)   %>
        </td>
        <td style="text-align:left;">
          <%= purge_data.try(:deletion) %>
        </td>
        <td style="text-align:left;">
          <%= purge_data.try(:run_by) %>
        </td>
        <td style="text-align:left;">
          <%= purge_data.try(:run_at) %>
        </td>
        <td style="text-align:left;">
          <%= purge_data.try(:table_name) %>
        </td>
        <td style="text-align:left;">
          <%= purge_data.try(:fault_reason) %>
        </td>
        <td style="text-align:left;">
          <%= purge_data.try(:status) %>
        </td>
      </tr>
    <% end %>
  </div>
</table>

qg-datapurge-125952a94e2a2233a62dc9293493b73ed2d4c89f/app/views/purgings/purging_request_form.html.erb
<script>

  $(document).ajaxSend(function(r, s) {
    $("#spinner_area").show();
  });

  $(document).ajaxStop(function(r, s) {
    $("#spinner_area").hide();
  });

  $(document).ready(function(){
    $('#one_day').prop('disabled',true);
    $('#two_day').prop('disabled',true);
    $('#three_day').prop('disabled',true);
  	$("#table_name").on("change", function () {
      if ($('#table_name').val() == 'NS_PENDING_NOTIFICATION'){
        $('#from_date').prop('disabled',true);
        $('#from_date').val('');
        $('#one_day').prop('disabled',false);
        $('#two_day').prop('disabled',false);
        $('#three_day').prop('disabled',false);
      }
      if ($('#table_name').val() != 'NS_PENDING_NOTIFICATION'){
        $('#from_date').prop('disabled',false);
        $('#one_day').prop('disabled',true);
        $('#two_day').prop('disabled',true);
        $('#three_day').prop('disabled',true);

      }
    })
    $("#generate_report_btn").on('click', function(e){
      $("#msg-error").text("")
      e.preventDefault
      var from_date = $("#from_date").val();
      var to_date = $("#to_date").val();
      var table_name = $("#table_name").val();
      if (table_name != "NS_PENDING_NOTIFICATION")
       { 
          if (from_date == "" || from_date == undefined || table_name == "" || table_name == undefined){
            $("#msg-error").text("Please select table name")
            return false
          }
          else if(from_date != ""){
            
            var start_date = new Date(from_date)
            var today = new Date()

            diff = (today - start_date)/1000/60/60/24

            if (start_date > today){
              $("#msg-error").text("Please don't select future date.");
              return false;
            }

            if (diff < 90){
              $("#msg-error").text("Date must be 90 days back.");
              return false;
            }
          }
      }    
    });
  })

</script>


<div id="spinner_area" style="float-left:100px;margin-left:550px;height:100px;width:100px;margin-top:10px;display:none;">
  <%= image_tag "spinner_gif.gif",size: "80x80" %>
  please wait....
</div>

<br/>
<h1>Data Purge Request</h1>
<br/>

<%= form_tag(purging_request_purgings_path, :method=>"get",:remote=>true ,:class=>'form-horizontal') do %>
  <div class="control-group">
    <%= label_tag 'Table Name' %>
    <%= select_tag :table_name, options_for_select([['FUNDS_TRANSFERS', 'FUNDS_TRANSFERS'],['INWARD_REMITTANCES', 'INWARD_REMITTANCES'],['ECOL_TRANSACTIONS', 'ECOL_TRANSACTIONS'],['NS_PENDING_NOTIFICATION','NS_PENDING_NOTIFICATION']]), :prompt => 'Select table' %>
  </div>
  <div class="control-group">
    <%= label_tag 'From Date' %>
    <%= text_field_tag "from_date" %>
  </div>
  <div class="control-group">
    One Day Before  <input class="control-group" type="radio" value="1" checked="checked" name="deletion_period[return]" id="one_day"><br/>

    Two Day Before <input class="control-group" type="radio" value="2" checked="checked" name="deletion_period[return]" id="two_day"><br/>

    Three Day Before <input class="control-group" type="radio" value="3" checked="checked" name="deletion_period[return]" id="three_day">
    <div class="form-actions"><br/>
  </div>

    <%= submit_tag "PURGE DATA",:class=>"btn btn-primary", :id => "generate_report_btn", data:{disable_with: "Please wait..."} %>
    <br/>
    <br/>
    <div id="msg-error"></div>
  </div>
<% end %>
<div id="data_area" style="dispaly:none;"></div>